version: '3.8'

services:
  mongo-todo:
    image: mongo
    container_name: mongo-todo
    ports:
      - "27017:27017"
    volumes:
      - /Users/donadinaev/Documents/Learning/todo-service/data/db:/data/db

  todo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-service
    depends_on:
      - mongo-todo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo-todo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: todo
